minecraft_version: 1.21.6 # supports up to 1.21.6
host: 127.0.0.1 # or "localhost", "your.ip.address.here"
port: 55916

bots:
  - username: Nano # bot's Minecraft username
    model: auto # model name (e.g., gpt-4o-mini, gemini-2.5-flash)
    provider: andy # model provider (e.g., openai, gemini, ollama). Set to Andy API by default
    personality: "You are helpful and friendly." # short description of how the bot should behave
    look_at_player: true # whether this bot should auto-look at nearby players
    save_conversation: false # if true, save conversation history to a file and reload on restart
    action_chat_feedback: false # send command outputs in Minecraft (e.g. "No zombie found nearby to attack" when using !attack). This may clutter the chat.
    action_conversation_feedback: false # add command outputs to conversation history. This gives the model slightly extra context on the current situation.

  # - username: GPT
  #   model: gpt-4o-mini
  #   provider: openai
  #   personality: "Act like a chill bro that uses slang."
  #   look_at_player: true
  #   save_conversation: false
  #   action_chat_feedback: false
  #   action_conversation_feedback: true

  # - username: Andy
  #   model: sweaterdog/andy-4:latest # ATTENTION: Sweaterdog's Andy models are not fully supported. Use at your own risk.
  #   provider: ollama
  #   personality: "Mine. Craft. Conquer."
  #   look_at_player: true
  #   save_conversation: true
  #   action_chat_feedback: true
  #   action_conversation_feedback: false
